config/routes.rb
Rails.application.routes.draw do
  constraints(NoSubdomain) do
    root 'static_pages#home'
    get "/select_account", :controller => "static_pages", :action => "select_account"
    get "/unis", :controller => "static_pages", :action => "unis"
    get "/download_uni_doc", :controller => "static_pages", :action => "download_uni_doc"

    # Interested Users
    get "/yes", :controller => "interested_users", :action => "new"
    resources :interested_users, only: [:create]
    get "/leaderboard", :controller => "interested_users", :action => "index"
    get "/feedback", :controller => "feedbacks", :action => "index"
  end

  constraints(HasSubdomain) do
    root 'bookings#home'
    devise_for :users, :controllers => { registrations: 'users/registrations' }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :rooms, only: [:show, :index] do
      resources :room_comments, only: :create
    end
    resources :feedbacks, only: [:new, :create]
    resources :posts, except: [:new]
    resources :post_replies, only: [:create]
    namespace :admin do
      resources :rooms, only: [:new, :create, :edit, :update] do
        resources :room_facilities, only: [:new, :create]
      end
      resources :facilities, only: [:new, :create]
      resources :bookings, only: [:index]
      get "/dashboard", :controller => "static_pages", :action => "dashboard"
      resources :room_comments, only: [:index]
      resources :whitelisted_emails, only: [:index, :create]
    end
    resources :users
    resources :bookings, except: [:index] do
      member do
        patch :add_user
        put :add_user
        patch :remove_user
        put :remove_user
      end
    end
    get "/home", :controller => "bookings", :action => "home"
    get "users/validation/check_email", :controller => "users", :action => "check_email"
  end
  
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :account
  has_many :user_instruments, inverse_of: :user, dependent: :destroy
  has_many :user_comments
  has_many :user_bookings, dependent: :destroy
  has_many :bookings, through: :user_bookings
  has_many :posts
  has_many :post_replies
  has_many :feedbacks
  mount_uploader :avatar, AvatarUploader

  accepts_nested_attributes_for :user_instruments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # validate :email_is_whitelisted

  def self.search(params)
    search_scope = User.joins(:user_instruments)

    if params[:name].present?
      search_scope = search_scope.where("lower(CONCAT(firstname,' ',surname)) LIKE lower(?)", "%#{params[:name]}%")
    end

    if params[:instrument_id].present?
      params[:instrument_id].reject!{ |id| id.blank? }
      search_scope = search_scope.where(
        "user_instruments.instrument_id": params[:instrument_id]
      )
    end

    if params[:genre_id].present?
      # params[:genre_id].reject! { |id| id.blank? }
      search_scope = search_scope.where(
        "user_instruments.genre_id": params[:genre_id]
      )
    end

    search_scope.distinct.order(:created_at)
  end

  def unique_instruments
    instruments = []
    user_instruments.each do |ui|
      instruments << ui.instrument.name
    end
    instruments.uniq
  end

  def unique_genres
    genres = []
    user_instruments.each do |ui|
      genres << ui.genre.name
    end
    genres.uniq
  end

  def instrument_bracket_genres
    grouped_array = []
    user_instruments.all.group_by(&:instrument_id).each do |instrument_id, user_instruments|
      individual_array = []
      individual_array << Instrument.find(instrument_id).name
      genre_array = []
      user_instruments.each do |user_instrument|
        genre_array << Genre.find(user_instrument.genre_id).name
      end
      individual_array << genre_array
      grouped_array << individual_array
    end
    grouped_array
  end
  
  def fullname
    "#{self.firstname} #{self.surname}"
  end

  def email_is_whitelisted
    domain = email.split("@", 2).last
    if !WhitelistedEmail.where("email_or_domain = ? OR email_or_domain = ?", domain, email).exists?
      errors.add(:email, "Your email address has not been approved")
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    resource = build_resource({})
    resource.user_instruments.build
    respond_with resource
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    if resource.user_instruments.empty?
      self.resource.user_instruments.build
    end
    super
  end

  # PUT /resource
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    # prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)
    resource.user_instruments = []
    resource_updated = resource.update_without_password(account_update_params)
    yield resource if block_given?
    if resource_updated
      # if is_flashing_format?
      #   flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
      #     :update_needs_confirmation : :updated
      #   set_flash_message :notice, flash_key
      # end
      bypass_sign_in resource, scope: resource_name
      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :firstname,
      :surname,
      :description,
      :avatar,
      :user_instruments_attributes => [:instrument_id, :genre_id]
    ])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [
      :firstname,
      :surname,
      :description,
      :avatar,
      :user_instruments_attributes => [:instrument_id, :genre_id]
    ])
  end

  protected

  def sign_up_params
    user_params = super
    user_params.merge(account: current_account)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   home_url(subdomain: resource.account.subdomain)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  private

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    root_url
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show]
  before_action :check_account_matches_user, only: [:index, :show]

  def index
    @users = current_account.users.where.not(id: current_user.id).search(search_params).paginate(:page => params[:page], :per_page => 21)
    @recent_bookings = current_account.bookings.where("(start_time > ?)", Time.now - 6.month).order(:start_time)


    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @user = current_account.users.find_by_id(params[:id])
    @user_recent_bookings = @user.bookings.where("(start_time > ? AND start_time < ?)", Time.now - 6.month, Time.now)
    @user_future_bookings = @user.bookings.where("(start_time > ?)", Time.now)
    @posts = @user.posts
  end

  def check_email
    @user = current_account.users.find_by_email(params[:user][:email])

    respond_to do |format|
      format.json { render :json => !@user }
    end
  end

  private
  def search_params
    params.permit(:name, :genre_id => [], :instrument_id => [])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class = "room-user-hero">
  <div class = "container">
    <div class = "row">
      <div class = "col-12 my-2 background-pink">
        <h1 class = "text-yellow">Find other musicians!</h1>
        <h5 class = "text-white"><strong>Search or filter</strong> by instrument and genre</h5>
        <div class="btn btn-secondary col-10 offset-1 toggle-search mt-2"><i class="fa fa-filter" aria-hidden="true"></i> Filter</div>
        <div class = "search-and-filter show-hide">
          <div class = "row mb-2">
            <%= form_tag(users_path, method: :get, class: "col-12" ) do %>
              <%= text_field_tag :name, params[:name], placeholder: "Search users by name", class: "col-12 col-md-4 mt-2 mx-0" %>
              <p class = "mb-0 mt-2 text-white">Instrument: </p>
              <div class = "col-6 col-md-3 my-2 mx-0">
                <%= select_tag :instrument_id, options_from_collection_for_select(Instrument.all, :id, :name, params[:instrument_id]), multiple: true, class: "multiselect" %>
              </div>
              <p class = "mb-0 mt-2 text-white">Genre: </p>
              <div class = "col-6 col-md-3 my-2 mx-0">
              <%= select_tag :genre_id, options_from_collection_for_select(Genre.all, :id, :name, params[:genre_id]), multiple: true, :class => "multiselect" %>
              </div>
              <%= submit_tag "Search", class: "btn btn-primary col-12 col-md-2 mt-2" %>
            <% end %>
          </div>
        </div>
        <div class = "col-12">
          <hr class = "mt-2 mb-4">
        </div>
      </div>
    </div>
    <div class = "row">
      <% @users.each do |user| %>
        <div class = "col-md-4 mb-5">
          <div class = "booyah-box col-12 px-0">
            <%= link_to user_path(user) do %>
              <div class = "top-half-booyah-box mx-0 text-center">
                <% if user.avatar.present? %>
                  <%= image_tag(user.avatar, class: "user-image-circle my-3") %>
                <% else %>
                  <%= image_tag('placeholder-user-profile.png', class: "user-image-circle my-3") %>
                <% end %>
                <h3 class = "mt-0"><%= user.fullname %></h3>
              </div>
            <% end %>
            <div class = "row">
              <div class = "col-12">
                <h4 class = "ml-3 mb-1">Instruments:</h4>
                <div class = "col-11 offset-1">
                  <% user.unique_instruments.each do |instrument| %>
                    <span class = "badge badge-default"><%= instrument %></span>
                  <% end %>
                </div>
              </div>  
            </div>
            <div class = "row">
              <div class = "col-12">
                <h4 class = "ml-3 mb-1">Genres:</h4>
                <div class = "col-11 offset-1">
                  <% user.unique_genres.each do |genre| %>
                    <span class = "badge badge-default"><%= genre %></span>
                  <% end %>
                </div>
              </div>  
            </div>
            <div class = "row">
              <div class = "col-12">
                <hr class = "my-2">
              </div>
            </div>
            <div class = "row">
              <div class = "col-12">
                <% user_recent_bookings = [] %>
                <% @recent_bookings.each do |booking| %>
                  <% if booking.users.any?{|booking_user| booking_user.id == user.id } %>
                    <% user_recent_bookings << booking %>
                  <% end %>
                <% end %>
                <p class = "green-text ml-3"><i class="fa fa-calendar" aria-hidden="true"></i><strong> <%= user_recent_bookings.length %></strong> bookings in past 6 months</p>
              </div>
            </div>
          </div>
        </div>
        <br />
      <% end %>
    </div>
    <div class = "row">
      <div class = "text-center">
        <div class = "digg_pagination py-2">
          <%= will_paginate @posts, :page_links => false %>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(function() {
    $('.multiselect').multiselect();

    $('.toggle-search').click(function(){
      $('.search-and-filter').slideToggle();
    });
  });
</script>

app/views/users/index.js.erb
$('#users-for-selection').html("<%= escape_javascript(render partial: "bookings/booking_user", collection: @users, as: :booking_user) %>");


//For each returned result, if you can find the id in selected users, add a class of active-user
$('.user-box').each(function (index) {
  if ($(".selected-users").find('[data-selecteduserid="' + $(this).data("userid") + '"]').length > 0) {
    $(this).addClass("active-user");
  };
});

app/views/users/show.html.erb
<div class = "container my-3">
  <div class = "row">
    <div class = "top-half-booyah-box col-12 mx-0 text-center">
      <% if @user.avatar.present? %>
        <%= image_tag(@user.avatar, class: "user-image-circle mt-3 mb-1") %>
      <% else %>
        <%= image_tag('placeholder-user-profile.png', class: "user-image-circle mt-3 mb-1") %>
      <% end %>
      <h1 class = "mt-2"><%= @user.fullname %></h1>
      <% if current_user == @user %>
        <%= link_to edit_user_registration_path do %>
          <div class = "btn btn-secondary mb-3"><i class = "fa fa-pencil" aria-hidden="true"></i> Edit profile</div>
        <% end %>
      <% else %>
        <%= mail_to @user.email do %>
          <div class = "btn btn-secondary mb-3"><i class="fa fa-envelope-o" aria-hidden="true"></i> Email <%= @user.firstname %></div>
        <% end %>
      <% end %> 
    </div>

    <div class = "bottom-half-booyah-box col-12 mx-0">
      <div class = "row">
        <div class = "col-12 col-md-6 mb-2">
          <div class = "col-10 offset-1 my-4 text-left px-0">
            <div class = "top-half-booyah-box-secondary">
              <h4 class = "text-center mt-1 ml-0"><%= @user.firstname %>'s Music</h4>
            </div>
            <div class = "bottom-half-booyah-box">
              <% if @user.description.present? %>
                <div class = "col-12">
                  <h4 class = "ml-0 mb-1">Description:</h4>
                  <div class = "col-11 offset-1 px-0">
                    <p><%= @user.description %></p>
                  </div>
                </div> 
              <% end %>
              <div class = "col-12 pt-2">
                <h4 class = "ml-0 mb-1">Instruments and genres</h4>
                <div class = "col-11 offset-1 px-0">
                  <% @user.instrument_bracket_genres.each do |grouped_user_instrument| %>
                    <strong><%= grouped_user_instrument[0] %></strong>:
                    <%= grouped_user_instrument[1].to_sentence %>
                    <br />               
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>

      <!-- Activity box -->
        <div class = "col-12 col-md-6 mb-2">
          <div class = "col-10 offset-1 booyah-box my-4 text-left px-0">
            <div class = "top-half-booyah-box-secondary">
              <h4 class = "text-center mt-1 ml-0"><%= @user.firstname %>'s Activity</h4>
            </div>
            <div class = "col-10 offset-1 mt-2">
              <p class = "green-text"><i class="fa fa-arrow-circle-o-left" aria-hidden="true"></i></i> <strong><%= @user_recent_bookings.length %></strong> bookings in past 6 months</p>
              <% if @user_recent_bookings.length > 0 %>
                <p class = "green-text"><i class="fa fa-play" aria-hidden="true"></i> Last booking on <strong><%= @user_recent_bookings.last.start_time.strftime("%A, %e %b %Y") %></strong></p>
              <% end %>
              <p class = "green-text"><i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> <strong><%= @user_future_bookings.length %></strong> upcoming bookings</p>
              <p><i class="fa fa-history" aria-hidden="true"></i> Member since <%= @user.created_at.strftime("%B %Y") %></p>
            </div>
          </div>
        </div>
      </div>
      <% if @posts.length > 0 %>
        <hr />
        <div class = "col-12">
          <h3><%= @user.firstname %>'s posts</h3>
          <% @posts.each do |post| %>
            <div class = "col-12 mb-2">
              <div class = "top-half-booyah-box-secondary px-2 py-2">
                <h5 class = my-0><%= link_to post.title, post_path(post) %></h5>
              </div>
              <div class = "bottom-half-booyah-box px-2">
                <p><%= post.message %></p>
                <small class = "text-muted">Posted by <%= link_to post.user.fullname, user_path(post.user) %> on <%= post.created_at.strftime('%A, %b %d, %Y') %> in <%= link_to post.humanized_category, posts_path(:categories => post.category) %> 
                  <%= link_to post_path(post) do %>
                    <span class = "badge badge-info">
                      <i class="fa fa-comment-o" aria-hidden="true"></i>
                      <%= post.post_replies.length %>
                    </span>
                  <% end %>
                </small>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>