config/routes.rb
Rails.application.routes.draw do
  constraints(NoSubdomain) do
    root 'static_pages#home'
    get "/select_account", :controller => "static_pages", :action => "select_account"
    get "/unis", :controller => "static_pages", :action => "unis"
    get "/download_uni_doc", :controller => "static_pages", :action => "download_uni_doc"

    # Interested Users
    get "/yes", :controller => "interested_users", :action => "new"
    resources :interested_users, only: [:create]
    get "/leaderboard", :controller => "interested_users", :action => "index"
    get "/feedback", :controller => "feedbacks", :action => "index"
  end

  constraints(HasSubdomain) do
    root 'bookings#home'
    devise_for :users, :controllers => { registrations: 'users/registrations' }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :rooms, only: [:show, :index] do
      resources :room_comments, only: :create
    end
    resources :feedbacks, only: [:new, :create]
    resources :posts, except: [:new]
    resources :post_replies, only: [:create]
    namespace :admin do
      resources :rooms, only: [:new, :create, :edit, :update] do
        resources :room_facilities, only: [:new, :create]
      end
      resources :facilities, only: [:new, :create]
      resources :bookings, only: [:index]
      get "/dashboard", :controller => "static_pages", :action => "dashboard"
      resources :room_comments, only: [:index]
      resources :whitelisted_emails, only: [:index, :create]
    end
    resources :users
    resources :bookings, except: [:index] do
      member do
        patch :add_user
        put :add_user
        patch :remove_user
        put :remove_user
      end
    end
    get "/home", :controller => "bookings", :action => "home"
    get "users/validation/check_email", :controller => "users", :action => "check_email"
  end
  
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :account
  has_many :bookings
  has_many :room_comments
  has_many :room_facilities
  has_many :facilities, through: :room_facilities
  accepts_nested_attributes_for :room_facilities

  mount_uploader :photo, PhotoUploader
end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < ApplicationController
  before_action :authenticate_user!, :authenticate_is_admin, :check_account_matches_user

  def new
    @room = Room.new
  end

  def create
    @room = current_account.rooms.create(room_params)
    redirect_to new_admin_room_room_facility_path(@room)
  end

  def edit
    @room = current_account.rooms.find_by_id(params[:id])
  end

  def update
    @room = current_account.rooms.find_by_id(params[:id])
    @room.update_attributes(room_params)
    redirect_to room_path(@room)
  end

  private

  def room_params
    params.require(:room).permit(:name, :address, :capacity, :photo)
  end

  helper_method :current_room
  def current_room
    @current_room ||= Room.find_by_id(params[:id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, :check_account_matches_user

  def index
    @rooms = current_account.rooms.order(:id)
    @user_bookings = current_user.bookings.where("(start_time > ?)", Time.now)
  end

  def show
    @room = current_account.rooms.find_by_id(params[:id])
    @room_comment = @room.room_comments.new
    @bookings = current_user.bookings.where("(room_id = ? AND start_time > ?)", @room.id, Time.now).sort_by{|booking| booking.start_time}
  end

  private

  helper_method :current_room
  def current_room
    @current_room ||= Room.find_by_id(params[:id])
  end
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<div class = "room-user-hero">
  <div class = "container">
    <div class = "row">
      <div class = "col-12 my-2 background-pink">
        <h1 class = "my-2 text-white">See all rooms and facilities</h1>
      </div>
    </div>
  </div>
  <div class = "container">
    <div class = "row">
      <% @rooms.each do |room| %>
        <div class = "col-md-4 mb-5">
          <%= link_to room_path(room) do %>
            <div class = "top-half-booyah-box mx-0 text-center">
              <% if room.photo.present? %>
                <%= image_tag(room.photo, class: "user-image-circle my-3") %>
              <% else %>
                <%= image_tag('instruments_placeholder.jpg', class: "user-image-circle my-3") %> 
              <% end %>
              <h3 class = "mt-0"><%= room.name %></h3>
            </div>
          <% end %>
          <div class = "bottom-half-booyah-box">
            <h4 class = "ml-3 mb-1">Facilities:</h4>
            <div class = "col-11 offset-1 my-2">
              <p><i class="fa fa-users" aria-hidden="true"></i> Capacity: <%= room.capacity %></p>
              <% room.facilities.each do |facility| %>
                <span class = "badge badge-default"><%= facility.full_facility %></span>
              <% end %>
            </div>
            <% user_room_bookings = [] %>
            <% @user_bookings.each do |booking| %>
              <% if booking.room == room %>
                <% user_room_bookings << booking %>
              <% end %>
            <% end %>
            <% if user_room_bookings.length > 0 %>
              <div class = "col-12">
                <hr class = "my-3">
              </div>
              <h4 class = "ml-3 mb-1">Bookings:</h4>
              <div class = "col-11 offset-1 my-2">
                <p class = "green-text mb-0"><i class="fa fa-calendar" aria-hidden="true"></i> You have <%= link_to "#{user_room_bookings.length} upcoming bookings", root_path %>  in this room</p>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class = "container my-3">
  <% if current_user.admin %>
    <h3>Admin options</h3>
    <div class = "row">
      <%= link_to "Edit room", edit_admin_room_path(@room), class: "btn btn-primary col-md-6" %>
      <%= link_to "Add a facility", new_admin_room_room_facility_path(@room), class: "btn btn-pink col-md-6" %>
    </div>
  <% end %>    

  <div class = "row top-half-booyah-box">
    <div class = "col-12 px-0 text-center mb-4">
      <% if @room.photo.present? %>
        <%= image_tag(@room.photo, class: "user-image-circle mt-5 mb-1") %>
      <% else %>
        <%= image_tag('instruments_placeholder.jpg', class: "user-image-circle mt-5 mb-1") %>
      <% end %>
      <h1 class = "mt-2"><%= @room.name %></h1>
    </div>
  </div>
  <div class = "row bottom-half-booyah-box py-3 mb-3">
    <div class = "col-md-6 mb-3">
      <div class = "col-12 booyah-box pb-2">
        <h3 class = "mt-3 mb-2"><i class="fa fa-music" aria-hidden="true"></i> Facilities</h3>
        <div class = "col-12">
          <hr class = "mt-0 mb-3">
        </div>
        <p><i class="fa fa-users" aria-hidden="true"></i> Capacity: <%= @room.capacity %></p>
        <% @room.facilities.each do |facility| %>
          <span class = "badge badge-info"><%= facility.full_facility %></span>
        <% end %>
      </div>
    </div>
    <div class = "col-md-6">
      <div class = "col-12 booyah-box">
        <h3 class = "mt-3 mb-2"><i class="fa fa-info-circle" aria-hidden="true"></i> Information</h3>
        <div class = "col-12">
          <hr class = "mt-0 mb-3">
        </div>
        <p>Location: <%= @room.address %></p>
      </div>
    </div>
    <div class = "col-12">
      <h3><%= "You have #{@bookings.length} upcoming bookings here"%></h3>
    </div>
    <% if @bookings.length > 0 %>
      <% @bookings.each do |booking| %>
          <div class="col-12 col-sm-6 col-md-4">
            <div class="booyah-box">
              <div class = "row">
                <div class = "col-12">
                  <h3 class="mt-1 ml-2"><%= booking.start_time.strftime("%a, %e %b %Y") %></h3><div class = "clear"></div>
                </div>
                <div class = "col-2 text-center">
                  <i class="fa fa-clock-o ml-2" aria-hidden="true"></i>
                </div>
                <div class = "col-10">
                  <%= "#{booking.start_time.strftime("%H:%M")} - #{booking.end_time.strftime("%H:%M")}" %>
                </div>
                <div class = "col-2 text-center">
                  <i class="fa fa-map-marker ml-2" aria-hidden="true"></i>
                </div>
                <div class = "col-10">
                  <%= booking.room.name %>
                </div>
                <div class = "col-2 text-center">
                  <i class="fa fa-users ml-2" aria-hidden="true"></i>
                </div>
                <div class = "col-10">
                  <%= booking.user_list %>
                </div>
                  <%= link_to 'View booking', booking_path(booking), class: "btn btn-pink col-10 offset-1 my-2" %>
              </div>
            </div>
            <br />
          </div>
        <% end %>
    <% else %>
      <div class = "col-12">
        <div class="alert alert-warning col-10 offset-1" role="alert">
          <strong>Oh no!</strong> You have no upcoming bookings in this room :(
        </div>
      </div>
    <% end %>
    <br />
    <!-- Large modal -->
    <div class = "col-12">
      <button class="btn btn-primary col-10 offset-1" data-toggle="modal" data-target=".bd-example-modal-lg">Report any problems with this room</button>
    </div>
  </div>
</div>

<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
   <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Tell us something</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
        <%= simple_form_for @room_comment, url: room_room_comments_path(@room) do |f| %>
      <div class="modal-body">
          <%= f.input :category, collection: RoomComment::CATEGORIES %>
          <%= f.input :message %>
          
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit "Send message", class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>


