config/routes.rb
Rails.application.routes.draw do
  constraints(NoSubdomain) do
    root 'static_pages#home'
    get "/select_account", :controller => "static_pages", :action => "select_account"
    get "/unis", :controller => "static_pages", :action => "unis"
    get "/download_uni_doc", :controller => "static_pages", :action => "download_uni_doc"

    # Interested Users
    get "/yes", :controller => "interested_users", :action => "new"
    resources :interested_users, only: [:create]
    get "/leaderboard", :controller => "interested_users", :action => "index"
    get "/feedback", :controller => "feedbacks", :action => "index"
  end

  constraints(HasSubdomain) do
    root 'bookings#home'
    devise_for :users, :controllers => { registrations: 'users/registrations' }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :rooms, only: [:show, :index] do
      resources :room_comments, only: :create
    end
    resources :feedbacks, only: [:new, :create]
    resources :posts, except: [:new]
    resources :post_replies, only: [:create]
    namespace :admin do
      resources :rooms, only: [:new, :create, :edit, :update] do
        resources :room_facilities, only: [:new, :create]
      end
      resources :facilities, only: [:new, :create]
      resources :bookings, only: [:index]
      get "/dashboard", :controller => "static_pages", :action => "dashboard"
      resources :room_comments, only: [:index]
      resources :whitelisted_emails, only: [:index, :create]
    end
    resources :users
    resources :bookings, except: [:index] do
      member do
        patch :add_user
        put :add_user
        patch :remove_user
        put :remove_user
      end
    end
    get "/home", :controller => "bookings", :action => "home"
    get "users/validation/check_email", :controller => "users", :action => "check_email"
  end
  
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < ApplicationController
  before_action :authenticate_user!, :authenticate_is_admin, :check_account_matches_user
  
  def dashboard
    @users = current_account.users.all
    @recent_bookings = current_account.bookings.where("(start_time > ? AND end_time < ?)", Time.now - 3.month, Time.now)
    @upcoming_bookings = current_account.bookings.where("(start_time > ?)", Time.now)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end

  def unis

  end

  def select_account
    if current_user.present?
      redirect_to home_url(host: "#{current_account.subdomain}.#{current_host}")
    else
      @accounts = Account.all
    end
  end

  def download_uni_doc
    send_file(
      "#{Rails.root}/assets/docs/Seed_Music_University_Scheme",
      filename: "Seed Music University Scheme.pdf",
      type: "application/pdf"
    )
  end
end

app/helpers/admin/static_pages_helper.rb
module Admin::StaticPagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/static_pages/dashboard.html.erb
<div class = "container my-3">
  <div class = "row">
    <div class = "col-12 my-2 background-pink">
      <h1 class = "text-yellow">Admin dashboard</h1>
      <h5 class = "text-white">Manage rooms, bookings and user access</h5>
    </div>
  </div>
  <div class = "row">
    <div class = "col-12 col-sm-6 col-md-4">
      <h6>Rooms</h6>
      <%= link_to new_admin_room_path, class: "btn btn-primary mb-2 col-12" do %>
        <i class="fa fa-plus" aria-hidden="true"></i> Add a room
      <% end %>
      <%= link_to admin_room_comments_path, class: "btn btn-secondary mb-2 col-12" do %>
        <i class="fa fa-quote-left" aria-hidden="true"></i> View all room comments
      <% end %>
    </div>
    <div class = "col-12 col-sm-6 col-md-4">
      <h6>Users</h6>
      <%= link_to admin_whitelisted_emails_path, class: "btn btn-primary mb-2 col-12" do %>
        <i class="fa fa-users" aria-hidden="true"></i> Manage user access
      <% end %>
    </div>
    <div class = "col-12 col-sm-6 col-md-4">
      <h6>Bookings</h6>
      <%= link_to admin_bookings_path, class: "btn btn-primary mb-2 col-12" do %>
        <i class="fa fa-calendar" aria-hidden="true"></i> View all bookings
      <% end %>
    </div>
  </div>
</div>

<hr />

<div class = "container my-3">
  <div class = "row">
    <h4 class = "col-12">Usage statistics</h4>
    <div class = "col-6 col-md-4">
      <div class = "booyah-box background-mint text-center py-3">
        <h2 class = "text-white"><%= @users.length %></h2>
        <p class = "text-white">Users</p>
      </div>
    </div>
    <div class = "col-6 col-md-4">
      <div class = "booyah-box background-pink text-center py-3">
        <h2 class = "text-white"><%= distance_of_time_in_words(@recent_bookings.map(&:duration).inject(0, &:+)) %></h2>
        <p class = "text-white">booked in past 3 months</p>
      </div>
    </div>
    <div class = "col-6 col-md-4">
      <div class = "booyah-box background-yellow text-center py-3">
        <h2><%= @upcoming_bookings.length %></h2>
        <p>Upcoming bookings</p>
      </div>
    </div>
  </div>
</div>