config/routes.rb
Rails.application.routes.draw do
  constraints(NoSubdomain) do
    root 'static_pages#home'
    get "/select_account", :controller => "static_pages", :action => "select_account"
    get "/unis", :controller => "static_pages", :action => "unis"
    get "/download_uni_doc", :controller => "static_pages", :action => "download_uni_doc"

    # Interested Users
    get "/yes", :controller => "interested_users", :action => "new"
    resources :interested_users, only: [:create]
    get "/leaderboard", :controller => "interested_users", :action => "index"
    get "/feedback", :controller => "feedbacks", :action => "index"
  end

  constraints(HasSubdomain) do
    root 'bookings#home'
    devise_for :users, :controllers => { registrations: 'users/registrations' }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :rooms, only: [:show, :index] do
      resources :room_comments, only: :create
    end
    resources :feedbacks, only: [:new, :create]
    resources :posts, except: [:new]
    resources :post_replies, only: [:create]
    namespace :admin do
      resources :rooms, only: [:new, :create, :edit, :update] do
        resources :room_facilities, only: [:new, :create]
      end
      resources :facilities, only: [:new, :create]
      resources :bookings, only: [:index]
      get "/dashboard", :controller => "static_pages", :action => "dashboard"
      resources :room_comments, only: [:index]
      resources :whitelisted_emails, only: [:index, :create]
    end
    resources :users
    resources :bookings, except: [:index] do
      member do
        patch :add_user
        put :add_user
        patch :remove_user
        put :remove_user
      end
    end
    get "/home", :controller => "bookings", :action => "home"
    get "users/validation/check_email", :controller => "users", :action => "check_email"
  end
  
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-110021404-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-110021404-1');
    </script>

    <title>Seed Music</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.0/jquery.validate.min.js"></script>
    <meta name="viewport" content="initial-scale=1">
    <%= favicon_link_tag %>
  </head>

  <body id = "background-grey">
    <div id="flex-content-container">
      <nav class="navbar navbar-toggleable-sm navbar-inverse background-purple mb-0">
        <button class="navbar-toggler navbar-toggler-right collapsed" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span> </span>
          <span> </span>
          <span> </span>  
        </button>
        <% if user_signed_in? %>
          <%= link_to root_url(host: "#{current_user.account.subdomain}.#{current_host}"), class: 'navbar-brand' do %>
            <%= image_tag "SM_Logo.svg", height: '30', class: "d-inline-block align-top", alt: "Seed Music logo" %>
            Seed Music
          <% end %>
        <% else %>
          <%= link_to root_url(host: "www.#{current_host}"), class: 'navbar-brand' do %>
            <%= image_tag "SM_Logo.svg", height: '30', class: "d-inline-block align-top", alt: "Seed Music logo" %>
            Seed Music
          <% end %>
        <% end %>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-sm-0">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to rooms_url(host: "#{current_user.account.subdomain}.#{current_host}"), class: 'nav-link mx-1' do %>
                  <i class="fa fa-map-marker" aria-hidden="true"></i> Rooms
                <% end %>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" id="CommunityDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-users" aria-hidden="true"></i> Community <span class="badge badge-info">New</span>
                </a>
                <div class="dropdown-menu background-pink" aria-labelledby="CommunityDropdownMenuLink">
                  <%= link_to users_url(host: "#{current_user.account.subdomain}.#{current_host}"), class: "dropdown-item text-white" do %>
                    <i class="fa fa-user-circle" aria-hidden="true"></i> People
                  <% end %>
                  <%= link_to posts_url(host: "#{current_user.account.subdomain}.#{current_host}"), class: "dropdown-item text-white" do %>
                    <i class="fa fa-comments" aria-hidden="true"></i> Forum <span class="badge badge-info">New</span>
                  <% end %>
                </div>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "University Scheme", unis_url(host: "www.#{current_host}"), class: "nav-link" %>
              </li>
            <% end %>
          </ul>
          <ul class="navbar-nav float-right">
            <% if user_signed_in? %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" id="ProfileDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-smile-o" aria-hidden="true"></i> &nbsp<%= current_user.firstname %>
                </a>
                <div class="dropdown-menu background-mint" aria-labelledby="ProfileDropdownMenuLink">
                  <%= link_to user_url(current_user, host: "#{current_user.account.subdomain}.#{current_host}"), class: "dropdown-item text-white" do %>
                    <i class="fa fa-user" aria-hidden="true"></i> Profile
                  <% end %>
                  <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item text-white" do %>
                    <i class="fa fa-sign-out" aria-hidden="true"></i> Sign out
                  <% end %>
                </div>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Log in or Sign up', select_account_url(host: "www.#{current_host}"), class: 'btn btn-yellow mx-md-2' %>
              </li>
              <li class = "nav-item">
                <%= mail_to "hello@seedmusic.co.uk" do %>
                  <div class = "btn btn-pink">Contact us</div>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
      <% if notice.present? %>
        <p class="alert alert-info alert-autodismiss col-10 offset-1"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-danger alert-autodismiss col-10 offset-1"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    <div id="footer">
      <div class="container">
        <b>Useful links</b>
        <br />
        <% if user_signed_in? && current_user.admin %>
          <%= link_to 'Admin dashboard', admin_dashboard_url(host: "#{current_user.account.subdomain}.#{current_host}") %>
        <br />
        <% end %>
        <% if user_signed_in? %>
          <%= link_to 'Give feedback', new_feedback_url(host: "#{current_user.account.subdomain}.#{current_host}") %>
        <% end %>
      </div>
    </div>
  </body>
</html>

<script>
  window.setTimeout(function() {
    $(".alert-autodismiss").fadeTo(500, 0).slideUp(600, function(){
        $(this).remove(); 
    });
  }, 1000);

  $(function () {
    $('[data-toggle="tooltip"]').tooltip();

    $(".navbar-toggle").on("click", function () {
      $(this).toggleClass("active");
    });
  })
</script>